name: Checkout Lib
description: Only checkout files needed for library

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
        sparse-checkout: |
          .github
          lib
