version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    target-branch: dev
    labels:
      - "app"
      - "dependencies"

  - package-ecosystem: npm
    directory: /lib
    schedule:
      interval: daily
    labels:
      - "lib"
      - "dependencies"
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: "@types/node"
      - dependency-name: "@types/react"
      - dependency-name: typescript
    groups:
      vite:
        patterns:
          - "vite*"
        exclude-patterns:
          - "*plugin-react*"
      vitest:
        patterns:
          - "*vitest*"
      eslint:
        patterns:
          - "*eslint*"
