version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    target-branch: dev
    commit-message:
      prefix: "[app] "

  - package-ecosystem: npm
    directory: /lib
    schedule:
      interval: daily
    commit-message:
      prefix: "[lib] "
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: '@types/react'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: prettier
    ignore:
      - dependency-name: typescript
