name: Setup
description: install Node.js & pnpm

# https://github.com/vercel/swr/blob/main/.github/workflows/install/action.yml
# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      id: pnpm-install
      with:
        version: 8
        run_install: false
